name: Build and deploy Node.js app to Azure Web App - anonymouslyurs-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend   # <<< build only the backend app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install (prod only)
        run: npm ci --omit=dev

      # Ensure your package.json has "start": "node index.js"
      # and your server listens on process.env.PORT
      - name: Verify start script
        run: node -e "const p=require('./package.json'); if(!p.scripts?.start) process.exit(1)"

      # Create a ready-to-run zip (includes node_modules)
      - name: Create deployment package
        run: |
          cd ..
          zip -r backend-release.zip backend \
            -x "backend/.git/*" \
               "backend/.github/*" \
               "backend/tests/*" \
               "backend/**/.env*"    # don't ship local env files

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-release
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-release

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: anonymouslyurs-backend
          # slot-name: 'Production'   # optional; default is production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
          package: backend-release.zip
