name: Build and deploy Node.js app to Azure Web App - anonymouslyurs-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'  # Changed from 22.x to 18.x for better compatibility
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci  # Uses package-lock.json for reproducible builds

      - name: Create production package
        run: |
          # Remove devDependencies if you don't need them in production
          npm prune --production
          # Create a clean deployment package
          zip -r release.zip . -x "*.git*" "node_modules/.bin/*" "*.github/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD009DF7835E4AD8B4EE6E68C535E157 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C81D9A2678D34FEAB6D9B507CCB21453 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD5B79B86C9646888960A7B2EBB72C2E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'anonymouslyurs-backend'
          slot-name: 'Production'
          package: .
