name: Build and deploy Node.js app to Azure Web App - anonymouslyurs-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      # If your backend is plain JS, you can install prod-only.
      # If you transpile (TypeScript) or need dev tools to build, do `npm ci` then prune.
      - name: Install backend dependencies
        working-directory: backend
        run: |
          npm ci --omit=dev

      # If you DO have a build step (e.g., TS -> JS), uncomment:
      # - name: Build backend
      #   working-directory: backend
      #   run: npm run build

      - name: Create deployment zip (backend only)
        run: |
          cd backend
          zip -r ../backend-release.zip . \
            -x "node_modules/.cache/*" \
            -x "**/.git/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-release
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-release

      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: anonymouslyurs-backend
          package: backend-release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
